ReviewTitle の設計変更
git-baboo/easy-review pull request #147
Opened 2021-11-09 07:10 UTC by ltoppyl

## 🔨 Details of Changes

- ReviewTitle の設計の変更、主に、コンポーネントの設計の仕方を変更した

## ✅ Resolved Issues

- close #139 

## 🤝 Related Issues

- #139

2021-11-09 08:52 UTC, watagit requested changes

2021-11-09 08:52 UTC, watagit commented on src/components/review/ReviewTitle.tsx
> +        {`${owner}/${repo}`}
![imo](https://img.shields.io/badge/review-imo-yellow)
個人的には
```suggestion
        {owner}/{repo}
```
の方が簡潔で読みやすいかな〜と思うけどどうだろう 🤔

2021-11-09 08:52 UTC, watagit commented on src/components/review/ReviewTitle.tsx
> +const ReviewTitle = ({ owner, repo, pull }: Props) => {
![imo](https://img.shields.io/badge/review-imo-yellow)
このコンポーネントが担っている役割が設計変更前と変わっているので、コンポーネント名も改めた方が良いかもです！`PullRequestTitle`とか、見出し的な意味合いで`PullRequestHeading`などなど

2021-11-09 08:52 UTC, watagit commented on src/pages/review.tsx
> +import { Button, useToast } from '@chakra-ui/react';
![must](https://img.shields.io/badge/review-must-red)
この部分は1つにまとめちゃって ok!
```suggestion
import { Box, Container, HStack, Divider, Center, Button, useToast } from '@chakra-ui/react';
```

2021-11-10 09:33 UTC, ltoppyl commented on src/components/review/ReviewTitle.tsx
> +const ReviewTitle = ({ owner, repo, pull }: Props) => {
検討した結果、`PullRequestHeading` を今回は採用してみました。

2021-11-12 12:01 UTC, watagit approved these changes
👍

2021-11-12 15:37 UTC, mikiya1130 approved these changes
OK!

2021-11-12 15:37 UTC, merged