FAQ 画面の作成
git-baboo/easy-review pull request #200
Opened 2022-01-14 06:55 UTC by ltoppyl

## 🔨 変更内容
- FAQ画面の作成

## 📸 スクリーンショット
![easy-review-issue-194](https://user-images.githubusercontent.com/68209431/149464542-f2b6f0cb-1019-4124-8f69-6a2f4f2686ec.gif)

## ✅ 解決するイシュー
- close #194

## 🤝 関連するイシュー
- #194

2022-01-26 03:47 UTC, watagit commented on src/pages/faq.tsx
> +/* eslint-disable max-len */
![ask](https://img.shields.io/badge/review-ask-blue)
この部分って消したら手元でエラー出る感じかな？

2022-01-26 03:54 UTC, ltoppyl commented on src/pages/faq.tsx
> +/* eslint-disable max-len */
Yes

2022-01-26 04:53 UTC, mikiya1130 requested changes

2022-01-26 04:53 UTC, mikiya1130 commented on src/pages/faq.tsx
> +        <Alert status="warning" colorScheme="blue">
![must](https://img.shields.io/badge/review-must-red)
Figma のアイコン「！」じゃなくて「i」やな
Chakra UI の[Alertページ](https://chakra-ui.com/docs/feedback/alert)見る限り、これでよさそうかな
```suggestion
        <Alert status="info">
```

2022-01-26 04:53 UTC, mikiya1130 commented on src/pages/faq.tsx
> +          Organization の管理者の場合は Grant）を押す
![imo](https://img.shields.io/badge/review-imo-yellow)
@ltoppyl @watagit 
Figma とテキストが異なるけど、どっちが正しい？
少なくともどちらかが修正されて、Figma と実装が同じ状態になるべきだと思います

2022-01-26 04:53 UTC, mikiya1130 commented on src/pages/faq.tsx
> +          >
![imo](https://img.shields.io/badge/review-imo-yellow)
外部サイト行くので、このリンク別タブで開きたい派やけど、@watagit 含め意見あればお願いします

2022-01-26 04:53 UTC, mikiya1130 commented on src/pages/faq.tsx
> +          A. 以下の手順 を参考に、GitHub
![imo](https://img.shields.io/badge/review-imo-yellow)
@ltoppyl @watagit 
Figma でも入ってたけど、このスペースは必要？
```suggestion
          A. 以下の手順を参考に、GitHub
```

2022-01-26 04:53 UTC, mikiya1130 commented on src/pages/faq.tsx
> +          3. 完了
![imo](https://img.shields.io/badge/review-imo-yellow)
テンプレートリテラルで簡潔(って言うほどでもないけど、`<Link>`のせいで)＆ファイル1行目のESLint例外なくせそう
```suggestion
          {`A. 以下の手順 を参考に、GitHub の設定を確認してください。アプリケーションのアクセスが許可されていない可能性があります。

          1. GitHub の`}
          <Link
            href="https://github.com/settings/connections/applications/f36da358d46af3fd2862"
            color="teal.500"
          >
            設定画面
          </Link>
          {`へアクセス
          2. Easy Review を使いたい Organization を選び Request（あなたが Organization の管理者の場合は Grant）を押す
          3. 完了`}
```

2022-01-26 04:53 UTC, mikiya1130 commented on src/pages/faq.tsx
> +        <Text pt={3} fontSize="sm" lineHeight={5} whiteSpace="pre-line">
![nits](https://img.shields.io/badge/review-nits-lightgrey)
`whiteSpace`ってなんか影響与えてる？？
(ただし、下のテンプレートリテラル使う場合は必要なります)
```suggestion
        <Text pt={3} fontSize="sm" lineHeight={5}>
```

2022-01-27 14:21 UTC, watagit commented on src/pages/faq.tsx
> +          Organization の管理者の場合は Grant）を押す
@ltoppyl Figma の方に合わせる感じでおねがいします！

2022-01-27 14:22 UTC, watagit commented on src/pages/faq.tsx
> +          >
私も同じイメージ！

@ltoppyl 別タブで開くよう実装してもらえると助かります 🙇‍♂️

2022-01-27 14:23 UTC, watagit commented on src/pages/faq.tsx
> +          A. 以下の手順 を参考に、GitHub
ほんとや、全く気づかんかった、、
完全にタイポです

@ltoppyl スペースなしでお願いします！Figma は修正済みです

2022-01-28 04:24 UTC, watagit requested changes

2022-01-28 04:24 UTC, watagit commented on src/pages/faq.tsx
> +          3. 完了
![must](https://img.shields.io/badge/review-must-red)
リスト部分は Chakra UI の OrderedList と ListItem を使うのがベターなのでこちらでお願いします！

#### 参考資料
- [Chakra UI - List - Ordered List](https://chakra-ui.com/docs/data-display/list#ordered-list)

2022-01-28 04:24 UTC, watagit commented on src/pages/faq.tsx
> +          </Link>
![must](https://img.shields.io/badge/review-must-red)
`isExternal`を指定した方が簡潔に書けるのでこちらでお願いします 🙇‍♂️ 

```suggestion
          <Link
            isExternal
            color="teal.500"
          >
            設定画面
          </Link>
```

#### 参考資料

- [Chakra UI - Link - External Link](https://chakra-ui.com/docs/navigation/link#external-link)

2022-01-28 07:55 UTC, mikiya1130 commented on src/pages/faq.tsx
> +          </Link>
`href` も必要なので、これでお願いします
```suggestion
          <Link
            href="https://github.com/settings/connections/applications/f36da358d46af3fd2862"
            isExternal
            color="teal.500"
          >
            設定画面
          </Link>
```

2022-01-28 09:26 UTC, mikiya1130 commented on src/pages/faq.tsx
> +          以下の手順を参考に、GitHubの設定を確認してください。アプリケーションのアクセスが許可されていない可能性があります。
@ltoppyl @watagit
ここの改行やけど、HTML の仕様的に、半角スペース・改行・タブ辺りがひっくるめて半角スペース１つ分として扱われることで都合よくなってるのがあまり気に入らんねんけど、なにか良い改善方法ないかな？
80文字制限に引っかかって format されてんのは分かるけど
`2. Easy Review` のとこも同様

2022-01-28 09:26 UTC, mikiya1130 commented on src/pages/faq.tsx
> +          A.
@watagit 
`A.` はリスト化はしない？
具体的には、手法はリスト化じゃなくても良いけど、本文の２行目以降が`A.` の下に回り込まないようにはしない？

2022-01-29 01:44 UTC, ltoppyl commented on src/pages/faq.tsx
> +          以下の手順を参考に、GitHubの設定を確認してください。アプリケーションのアクセスが許可されていない可能性があります。
これ、自分もめっちゃ気になってて、どうにかならんかなーと思ってる

2022-01-29 02:21 UTC, watagit commented on src/pages/faq.tsx
> +          以下の手順を参考に、GitHubの設定を確認してください。アプリケーションのアクセスが許可されていない可能性があります。
@ltoppyl @mikiya1130 
プロジェクト内の ESLint の設定は文字制限を100文字に設定してるんやけど、何かしらが原因でフォーマットされてるというのが現状
私の手元だと"A. 以下の~"とか"2. Easy Review~"の部分を1行に収めても ESLint からの警告は出ないんよね
コミット時とかファイル保存時にプロジェクト以外のフォーマットが走ってる可能性があるから VSCode の設定とかを見てみてほしい

2022-01-29 02:36 UTC, mikiya1130 commented on src/pages/faq.tsx
> +          以下の手順を参考に、GitHubの設定を確認してください。アプリケーションのアクセスが許可されていない可能性があります。
@watagit 
あっ、そういうこと
なら prettier の `printWidth` かな？
ただ、やとしても100文字超えてるから、フォーマッタによって半角スペースで改行されてしまう問題は解決せんな、、、

2022-01-29 14:08 UTC, mikiya1130 approved these changes
色々対応ありがとう

2022-01-29 15:54 UTC, watagit requested changes

2022-01-29 15:54 UTC, watagit commented on src/pages/faq.tsx
> +    <Layout text={"よくある質問"} icon={AiFillQuestionCircle}>
![nits](https://img.shields.io/badge/review-nits-lightgrey)
ごめん、めちゃくちゃ細かいんやけど、String 型の値の渡し方を統一しといてもらえると助かる 🙇‍♂️ 
```suggestion
    <Layout text="よくある質問" icon={AiFillQuestionCircle}>
```

2022-01-30 00:35 UTC, ltoppyl commented on src/pages/faq.tsx
> +    <Layout text={"よくある質問"} icon={AiFillQuestionCircle}>
@watagit 
対応しました！

2022-01-31 12:09 UTC, watagit approved these changes
LGTM!!!

2022-01-31 14:45 UTC, mikiya1130 approved these changes

2022-02-01 02:15 UTC, merged