Spacer コンポーネントの実装
git-baboo/easy-review pull request #208
Opened 2022-01-25 04:29 UTC by ltoppyl

## 🔨 変更内容
- Spacer コンポーネントの実装

## 📸 スクリーンショット

## ✅ 解決するイシュー
- close #202

## 🤝 関連するイシュー
- #202

2022-01-25 11:36 UTC, watagit requested changes
可能な限りこの部分を Chakra UI に置き換える方針でやってみてほしい！
https://zenn.dev/def_yuisato/articles/replace-margin-with-spacer-in-react#spacer-%E5%AE%9F%E8%A3%85
- Props は size と horizontal の2種類
- Box に対して記事と同様に w, h, display, flexShrink を指定

#### イメージ
![spacer](https://user-images.githubusercontent.com/44804976/150969665-c654a2d1-76e4-44da-b236-6f2964e2d8bc.jpg)

2022-01-28 04:37 UTC, watagit requested changes

2022-01-28 04:37 UTC, watagit commented on src/components/Spacer.tsx
> +    <Box w={size} h={"auto"} display={"inline-block"} flexShrink={0}></Box>
![nits](https://img.shields.io/badge/review-nits-lightgrey)
この書き方の方が簡潔なのでこちらでいきましょう〜

```suggestion
    <Box w={size} h={"auto"} display={"inline-block"} flexShrink={0} />
```

2022-01-28 04:37 UTC, watagit commented on src/components/Spacer.tsx
> +    <Box w={"auto"} h={size} flexShrink={0}></Box>
![nits](https://img.shields.io/badge/review-nits-lightgrey)
こちらもおねがいしゃす！
```suggestion
    <Box w={"auto"} h={size} flexShrink={0} />
```

2022-01-28 04:37 UTC, watagit commented on src/components/Spacer.tsx
> +  horizontal: boolean;
![must](https://img.shields.io/badge/review-must-red)
horizontal はオプションで指定できるような設計でお願いします！
```suggestion
  horizontal?: boolean;
```

理由としては、以下のように横方向のスペース調整時に限り horizontal を指定したいからです

```tsx
// 縦方向
return (
  <>
    <ComponentA />
    <Spacer size={4} />
    <ComponentB />
  </>
)
```

```tsx
// 横方向
return (
  <Flex>
    <ComponentA />
    <Spacer size={4} horizontal />
    <ComponentB />
  </Flex>
)
```

2022-01-28 04:37 UTC, watagit commented on src/components/Spacer.tsx
> +    <Box w={size} h={"auto"} display={"inline-block"} flexShrink={0}></Box>
![nits](https://img.shields.io/badge/review-nits-lightgrey)
String 型の値を props に渡す際はより簡潔な記法で統一したいです〜
```suggestion
    <Box w={size} h="auto" display="inline-block" flexShrink={0}></Box>
```

2022-01-28 04:37 UTC, watagit commented on src/components/Spacer.tsx
> +    <Box w={"auto"} h={size} flexShrink={0}></Box>
![nits](https://img.shields.io/badge/review-nits-lightgrey)
こちらも
```suggestion
    <Box w="auto" h={size} flexShrink={0}></Box>
```

2022-01-28 07:50 UTC, mikiya1130 requested changes

2022-01-28 07:50 UTC, mikiya1130 commented on src/components/Spacer.tsx
> +  horizontal: boolean;
![imo](https://img.shields.io/badge/review-imo-yellow)
ついでに、`size`, `horizontal` の順番に入れ替えといてほしいかな
オプションは後方に置きたい
(動作には全く影響ないけど)

2022-01-28 07:50 UTC, mikiya1130 commented on src/components/Spacer.tsx
> +const Spacer = ({ horizontal, size }: Props) => {
![imo](https://img.shields.io/badge/review-imo-yellow)
[上のスレッド](https://github.com/git-baboo/easy-review/pull/208/files/14c8f5c2b829fbb5aef528e3d0ee6d5d0fb62d72#r794196560)の内容と合わせてデフォルト引数の指定をお願いします
```suggestion
const Spacer = ({ size, horizontal = false }: Props) => {
```

2022-01-29 01:57 UTC, mikiya1130 approved these changes
おっけー！

2022-01-29 02:13 UTC, watagit commented on src/components/Spacer.tsx
> +const Spacer = ({ size, horizontal = false }: Props) => {
![ask](https://img.shields.io/badge/review-ask-blue)
@mikiya1130 
デフォルト引数の設定を依頼してくれたと思うんだけど、意図としては"horizontal が指定されずに undefined になった場合の対応"という感じかな？
return 内で"horizontal が true か、そうでないか"で条件分岐してるから undefined になっても問題ない気がすると思って

2022-01-29 02:25 UTC, mikiya1130 commented on src/components/Spacer.tsx
> +const Spacer = ({ size, horizontal = false }: Props) => {
@watagit 
そのとおりです
`bool(undefined)` → `false` やから動作的には問題ないけど
より詳細にはこのあたりの理由かな

- `A ? B : C` の構文において `A` は `boolean` 型が想定されてるから、きちんとその型を渡す
- `<XXX />` と `<XXX horizontal={false} />` で動作が変わるかもしれないと、内部の実装を再確認することを防ぐ (型で条件分岐などもあり得るので)

2022-01-29 15:55 UTC, watagit commented on src/components/Spacer.tsx
> +const Spacer = ({ size, horizontal = false }: Props) => {
@mikiya1130 なるほど、意図が理解できた！設計的にその方が堅牢で良きだね 👍

2022-01-29 15:59 UTC, watagit commented on src/components/Spacer.tsx
> +const Spacer = ({ size, horizontal = false }: Props) => {
@mikiya1130 @ltoppyl 
完全に失念してたんだけど、Chakra UI で用意されてる Spacer と名前が被ってしまうからこのコンポーネント名は変えたほうが良きだよね 🤔 
コンポーネント名どんなのがいいかな？
マージンの役割を持ってるから`Margin`とかでもいいのかなと思っている

2022-01-29 23:13 UTC, mikiya1130 commented on src/components/Spacer.tsx
> +const Spacer = ({ size, horizontal = false }: Props) => {
ほかには

- `Separate` (`Separater`)
- `WhiteSpace`

あたり？？
もしくは、この `Spacer` はそのままで、これを Wrap する `VSpacer` と `HSpacer` を作成する作戦とか

```tsx
type Props = {
  size: number;
}

const VSpacer = ({size}: Props) => {
  return <Spacer size={size} />
};
```

```tsx
type Props = {
  size: number;
}

const HSpacer = ({size}: Props) => {
  return <Spacer size={size} horizontal />
};
```

2022-01-30 00:48 UTC, ltoppyl commented on src/components/Spacer.tsx
> +const Spacer = ({ size, horizontal = false }: Props) => {
個人的には、VSpacer, HSpacer 結構好きなんだけど、
そうするなら、
``` tsx
type Props = {
  size: number;
}

const VSpacer = ({size}: Props) => {
  return <Box w={size} h="auto" display="inline-block" flexShrink={0} />
};
```
``` tsx
type Props = {
  size: number;
}

const HSpacer = ({size}: Props) => {
  return <Box w="auto" h={size} flexShrink={0} />
};
```
でもいいのかなーと思ったり。

2022-01-31 12:11 UTC, watagit commented on src/components/Spacer.tsx
> +const Spacer = ({ size, horizontal = false }: Props) => {
@ltoppyl が提案してくれた実装の方がスマートで良さそうだな〜と感じた 👍 
一旦それでやってみようか

2022-02-01 03:20 UTC, watagit reviewed
H と V が逆な気がする 🤔 
horizontal:  水平方向のスペース調整（w を指定できる）
vertical: 垂直方向のスペース調整（h を指定できる）
っていう認識なんだけど、合ってるかな？

2022-02-01 03:38 UTC, ltoppyl commented
> H と V が逆な気がする 🤔 horizontal: 水平方向のスペース調整（w を指定できる） vertical: 垂直方向のスペース調整（h を指定できる） っていう認識なんだけど、合ってるかな？

2022-02-01 07:09 UTC, mikiya1130 reviewed
1ファイルに2つ記述かと思ってた
Chakra の HStack と VStack が1ファイルにあるのと同じ感じで
参考：https://github.com/chakra-ui/chakra-ui/blob/main/packages/layout/src/stack.tsx#L181-L201
それぞれがそんなに長くないのと、実装・役割的にも似てるから、(1フォルダにまとめるのもありやけど、むしろ、もはや)1ファイルにまとめておいてもいいんじゃない？って考え

2022-02-01 07:27 UTC, ltoppyl commented
``` tsx
export const Function = () => {}
```
``` tsx
const Function = () => {}

export default Function
```
この２つって同義なの！？

2022-02-01 07:32 UTC, mikiya1130 commented
> ```tsx
> export const Function = () => {}
> ```
> 
> ```tsx
> const Function = () => {}
> 
> export default Function
> ```
> 
> この２つって同義なの！？

- import の仕方が変わる
```tsx
import { Function } from "Function.tsx"
```
```tsx
import Function from "Function.tsx"
```
- 上は1ファイルにいくつでも書けるけど、下は1つまで
- 下は `Function` という名前でインポートしなくても良い

という理解(それ以外は変わらないという理解)

2022-02-01 07:34 UTC, ltoppyl commented
なるほどなるほど
最初 1つのファイルに書こうと思って、できんかったから、1つのファイルで書くように直します！

2022-02-01 07:35 UTC, mikiya1130 commented
1ファイルに書く予定やったならちょうど良かった
対応お願いいたします

2022-02-01 07:40 UTC, mikiya1130 approved these changes
素早い対応！

2022-02-02 03:49 UTC, watagit approved these changes
[![LGTM](https://www.lgtm.app/p/PGlMpO1fG)](https://www.lgtm.app/i/PGlMpO1fG)

2022-02-02 05:17 UTC, merged