signInWithRedirect への移行
git-baboo/easy-review pull request #226
Opened 2022-02-08 01:05 UTC by ltoppyl

## 🔨 変更内容
- ログイン処理に 現状 signInWithPopup を使用しいているのを signInWithRedirect に変更する

## 📸 スクリーンショット

## ✅ 解決するイシュー
- close #214

## 🤝 関連するイシュー
- #214

2022-02-08 02:34 UTC, mikiya1130 reviewed
動作は問題ないけど、ログイン後ログイン画面が割と長く表示されたままなのが気に入らんなー
最初バグってるかと思った

- 原因を分かってない
- 原因は分かってるけど直し方が分からない
- 原因が分かってて直し方も分かってるけど見て見ぬふりしてる

どれな感じ？
※「原因」は言い換えれば、ログイン後ログイン画面が表示されている間に裏で起こっていることかな

2022-02-08 02:45 UTC, ltoppyl commented
原因わかってないを見て見ぬ振り中です…

裏の動作に時間がかかってるんかなーと思ってるけど、どうなんでしょう！？

2022-02-08 02:54 UTC, mikiya1130 commented
> 原因わかってないを見て見ぬ振り中です…
> 
> 裏の動作に時間がかかってるんかなーと思ってるけど、どうなんでしょう！？

例えば怪しいとこ・変数をコンソールでデバッグするとかで、どの処理が裏で行われてるせいなのかだけでも分かると、解消できなくてもローディングを表示させるとかも考えれるから嬉しいな(これやるなら、それは別Issueやけど)
と言っても無駄に時間消費も良くないのでほどほどに、、、
@watagit が原因・解決法知ってたりする？？

2022-02-09 07:38 UTC, watagit commented
ちょっと原因探ってみます〜！

2022-02-09 07:41 UTC, watagit commented
@ltoppyl `getRedirectResult`メソッドを使うにあたって参考にした資料とかドキュメントがあれば共有してほしい！

2022-02-09 07:49 UTC, ltoppyl commented
https://firebase.google.com/docs/auth/web/github-auth?hl=ja
これ参考にしました

2022-02-09 08:46 UTC, watagit commented
@ltoppyl @mikiya1130 
色々調べてみたけど、そもそも Firebase Auth が全体的にもっさりしてる説がある（要調査）
- [Twitter](https://twitter.com/search?q=firebase%20auth%20%E9%81%85%E3%81%84&src=typed_query&f=top)
- [Firebase Authentication のパフォーマンスを計測してみた](https://blog.odan.dev/articles/2020/09/firebase-auth-benchmark)

UX に影響を与えかねない部分でもあるから、このプルリクではひとまず速度は考えず、別イシューに切り出して次のリリースまでに対応する形でいかがでしょう！（次回の定例で次のリリースについて決めよう）

2022-02-09 10:02 UTC, mikiya1130 approved these changes

2022-02-09 10:09 UTC, watagit commented on src/hooks/useAuth.ts
> -import { Octokit } from "@octokit/rest";
<!--
タイポやバグなどを見つけたら早急に報告しましょう！
例）タイポしてるので修正お願いします！ reveiw > review
例）ローカルだと以下のようにレイアウトが崩れてしまっているので確認をお願いします！
-->
wow

2022-02-09 10:10 UTC, watagit commented on src/hooks/useAuth.ts
> -import { Octokit } from "@octokit/rest";
Easy Review のテストコメントです！

2022-02-09 10:12 UTC, watagit requested changes

2022-02-09 10:12 UTC, watagit commented on src/pages/index.tsx
> +  const provider = new GithubAuthProvider();
![nits](https://img.shields.io/badge/review-nits-lightgrey)
使ってなさそうなので消しちゃいましょう〜 👍

2022-02-10 00:56 UTC, ltoppyl commented on src/pages/index.tsx
> +  const provider = new GithubAuthProvider();
修正しましたー！

2022-02-10 02:46 UTC, watagit approved these changes

2022-02-10 07:59 UTC, mikiya1130 approved these changes

2022-02-11 01:57 UTC, merged