CommentListItem 内のマージン周りのリファクタリング
git-baboo/easy-review pull request #239
Opened 2022-02-09 11:00 UTC by watagit

## 🔨 変更内容

- Stack を使ったほうがいい感じにコンポーネント間のマージン調整ができるため、List が使われていた部分を Stack に置き換えました。
- それに伴って微調整が入っています。

## ✅ 解決するイシュー

- close #238 

## 🤝 関連するイシュー

- #238

2022-02-10 01:42 UTC, ltoppyl commented on src/components/review/CommentListItem.tsx
> -    <ListItem m={2} p={4} border="1px" borderRadius="md" borderColor="gray.300">
![ask](https://img.shields.io/badge/review-ask-blue.svg)
`<ListItem>` にあった、`m={2}` ってどこにいった？？

2022-02-10 02:42 UTC, watagit commented on src/components/review/CommentListItem.tsx
> -    <ListItem m={2} p={4} border="1px" borderRadius="md" borderColor="gray.300">
Widget.tsx 内の Stack がデフォルトで`spacing={2}`を持ってて、今回はそれで十分かなという判断をしてる！

`node_modules/@chakra-ui/layout/src/stack.tsx`の106行目に`spacing="0.5rem"`っていう記述があって、これは`spacing={2}`と同じ大きさ

[Chakra UI - Default Theme - Spacing](https://chakra-ui.com/docs/theming/theme#spacing)

2022-02-10 08:54 UTC, mikiya1130 commented on src/components/review/CommentListItem.tsx
> -    <ListItem m={2} p={4} border="1px" borderRadius="md" borderColor="gray.300">
(ひとりごと)
最初と最後の ListItem の外側の上下は、これまで margin 相殺になってたから、無くなっても変わりなし
左右の margin に関しては、無くなったことで少し横長に広がったけど、むしろ個人的にはこっちの方がいいかもと感じた(ので良し)

2022-02-10 08:54 UTC, mikiya1130 commented on src/components/review/CommentListItem.tsx
> -    <ListItem m={2} p={4} border="1px" borderRadius="md" borderColor="gray.300">
![ask](https://img.shields.io/badge/review-ask-blue)
@watagit 
Figma にコメントのプレビューが見当たらん気がするけど、どこ行った？
このコンポーネント作った当時はさすがにあったと思うねんけど？？

2022-02-10 08:54 UTC, mikiya1130 commented on src/components/review/Widget.tsx
> +        <Stack>
![imo](https://img.shields.io/badge/review-imo-yellow)
`<Stack direction={['column', 'row']}>` みたいに条件分岐したい場合を除いて、`HStack` `VStack` を利用したほうが分かりやすくていいかなと思う

2022-02-10 10:27 UTC, watagit commented on src/components/review/CommentListItem.tsx
> -    <ListItem m={2} p={4} border="1px" borderRadius="md" borderColor="gray.300">
コメントのプレビューって Figma にあったっけ？
この部分よね？
![screenshot](https://user-images.githubusercontent.com/44804976/153388032-09cca629-47e8-413d-9667-1c02775d4bfc.png)

2022-02-10 10:27 UTC, mikiya1130 commented on src/components/review/CommentListItem.tsx
> -    <ListItem m={2} p={4} border="1px" borderRadius="md" borderColor="gray.300">
うん

2022-02-10 10:30 UTC, watagit commented on src/components/review/CommentListItem.tsx
> -    <ListItem m={2} p={4} border="1px" borderRadius="md" borderColor="gray.300">
Figma の履歴見てる感じプレビューは作ってない気がするけど、あったほうがいいかな？
要望あれば作ります 👍

2022-02-10 10:32 UTC, mikiya1130 commented on src/components/review/CommentListItem.tsx
> -    <ListItem m={2} p={4} border="1px" borderRadius="md" borderColor="gray.300">
あれ？そうやったんか
「いい感じに」ってことで任されて作ったんやっけな
別に作らないでも大丈夫かな
ありがとう

2022-02-10 10:34 UTC, mikiya1130 commented on src/components/review/CommentListItem.tsx
> -    <ListItem m={2} p={4} border="1px" borderRadius="md" borderColor="gray.300">
@ltoppyl 
https://github.com/git-baboo/easy-review/pull/239#discussion_r803256045 を既読したら `Resolve conversation` でおっけーです

2022-02-10 10:51 UTC, watagit commented on src/components/review/Widget.tsx
> +        <Stack>
初めて知ったんだけど、`Stack`と`VStack`って若干挙動が違うんやね
|Stack|VStack|
|-|-|
|![スクリーンショット 2022-02-10 19 43 20](https://user-images.githubusercontent.com/44804976/153391058-ab735102-4b1c-4bb1-8fb8-114417054ec9.png)|![スクリーンショット 2022-02-10 19 43 03](https://user-images.githubusercontent.com/44804976/153391098-57aa0eea-e361-49c5-85d7-ee7a36548b50.png)|

この場合どっち使うべきやと思う？
Stack を使って（指定しなくても挙動は変わらんけど無駄な思考を減らす目的で）direction="column" を指定する or VStack を使って CommentListItem に w="full" を指定する

個人的には Stack を使って direction="column" を渡したほうが設計的にキレイな気がしてる（column を見てパッと縦並びを連想できるか些か不安ではある）
それ以外にもアイデアあったらお願いシャス

2022-02-10 11:15 UTC, mikiya1130 commented on src/components/review/Widget.tsx
> +        <Stack>
それは知らずにコメントしてた
`<Stack direction="column">` のんがいいかな

調べたところ、`align-items: center` が差の原因みたい
https://github.com/chakra-ui/chakra-ui/blob/main/packages/layout/src/stack.tsx#L196

2022-02-11 06:07 UTC, watagit commented on src/components/review/Widget.tsx
> +        <Stack>
ほええ〜そういうことなんやね 👀 
Stack に direction="column" を指定する形で実装しとこうと思います〜

2022-02-11 06:18 UTC, watagit commented on src/components/review/Widget.tsx
> +        <Stack>
修正 done 
https://github.com/git-baboo/easy-review/pull/239/commits/4d0e77e8614da315c1c336ceb33cccb211f93ddd

2022-02-11 06:19 UTC, watagit commented
@ltoppyl 
若干修正加えたのでお手すきの際に 🙏 
ここの差分だけ見てもらたら良きだと思う！
https://github.com/git-baboo/easy-review/pull/239/commits/4d0e77e8614da315c1c336ceb33cccb211f93ddd

2022-02-11 06:28 UTC, mikiya1130 requested changes
ごめん、ここのスペースが無くなってしまってることに気づいてしまった

![Screenshot-20220211152420-650x293](https://user-images.githubusercontent.com/63896499/153546457-1a0987b8-c4b6-49dd-a82f-def00b78d3be.png)

2022-02-11 06:51 UTC, watagit commented
@mikiya1130 
あーそうか、、
修正します

2022-02-11 08:30 UTC, watagit commented
@mikiya1130 
レビューコメント入力時にもスペースが入るよう修正しました〜
[38e8e9c](https://github.com/git-baboo/easy-review/pull/239/commits/38e8e9c2891aeef07eddf927c714278508940700)

2022-02-11 12:27 UTC, ltoppyl approved these changes
![LGTM](https://image.lgtmoon.dev/3699)

2022-02-13 06:37 UTC, merged