Templateの説明部分のコンポーネントを作成
git-baboo/easy-review pull request #37
Opened 2021-10-21 08:19 UTC by kacha-122

## 🔨 Details of Changes

- テンプレートの説明部分のコンポーネントを作成

## 📸 Screenshot

## ✅ Resolved Issues

- close #29

## 🤝 Related Issues

- #29

2021-10-21 11:18 UTC, watagit commented on src/components/Template.tsx
> +        </Box>
![must](https://img.shields.io/badge/review-must-red)
似たようなブロックが並んでいるので1つのコンポーネントに切り分けた方が良さそうです！
このファイル名を`TemplateList`とかにして、別コンポーネントとして`Template`を作る感じで
イメージ的には最終的に`TemplateList`がこんなふうに

```ts
const TemplateList = () => {
  return (
    <>
      <VStack spacing={5}>
        <TmpTemplate />
        <TmpTemplate />
        <TmpTemplate />
      </VStack>
    </>
  );
};
```

2021-10-21 12:44 UTC, watagit requested changes

2021-10-21 12:44 UTC, watagit commented on src/components/Template.tsx
> +  tmp: string;
![imo](https://img.shields.io/badge/review-imo-yellow)
`description`とかいかがでしょう！

2021-10-21 12:44 UTC, watagit commented on src/components/TemplateList.tsx
> +        <Template title={templates[2].title} tmp={templates[2].tmp} />
```suggestion
        {templates.map((template) => (
          <Template key={template.title} title={template.title} tmp={template.tmp} />
        ))}
```
の方がスマートかなと！

2021-10-21 12:58 UTC, ltoppyl commented on src/components/TemplateList.tsx
> +      '命名や設計がキレイなどの良いコードを見つけたときはポジティブな意見をバシバシ送っちゃいましょう！プルリクエストの作成者は嬉しいこと間違いなしです',
![nits](https://img.shields.io/badge/review-nits-inactive.svg)
「命名が…送っちゃいましょう！」と「プルリクエスト…」の間に改行を挟むようになったので、改行の追加をお願いしたいです！
テキスト全体を 「`」でくくって、改行させたいとこに「\n」を入れると改行できるはずです！
↑ここの部分をMarkdown上で表現するの難しい！
(TopPageのヘッダーのとこで改行使って表示させてます)

2021-10-21 12:59 UTC, ltoppyl commented on src/components/TemplateList.tsx
> +      'タイポや可読性の低いコードを見つけた場合は早急に報告しましょう！あなたの報告がプロダクトを改善します！',
![nits](https://img.shields.io/badge/review-nits-inactive.svg)
ここも、「あなたの報告が…」の前に改行をお願いします！

2021-10-21 13:18 UTC, watagit commented on src/components/TemplateList.tsx
> +    </>
![nits](https://img.shields.io/badge/review-nits-lightgrey)
一番外側の`<></>`は消しちゃって ok です！

2021-10-21 13:32 UTC, kacha-122 commented on src/components/TemplateList.tsx
> +      '命名や設計がキレイなどの良いコードを見つけたときはポジティブな意見をバシバシ送っちゃいましょう！プルリクエストの作成者は嬉しいこと間違いなしです',
[勉強用]
`whiteSpace="pre-line"` をTextのところに入れる必要あり

2021-10-22 00:59 UTC, ltoppyl commented
![LGTM](https://image.lgtmoon.dev/3699)

2021-10-22 01:46 UTC, watagit approved these changes

2021-10-22 01:46 UTC, merged